# Generated by Django 4.2 on 2023-04-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
                ('cycle', models.CharField(max_length=2)),
                ('myrequest', models.TextField()),
                ('order', models.CharField(max_length=300)),
                ('reason', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
