# Generated by Django 4.2 on 2023-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_fut_binary_content_fut_pdf_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='code',
            field=models.TextField(default='00000000000'),
        ),
    ]
